### PR TITLE
archive aliquot_covaris_microbial.py

### PR DESCRIPTION
**Pull request by barrystokman**
This PR archives `aliquot_covaris_microbial.py`

This PR can only be merged after the new EPP is deployed: see PR \<tbd>

**Review:**
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [x] **MINOR** - when you add functionality in a backwards compatible manner

### CODE REVIEW

**Comment by barrystokman** [comment]
```
(cg_lims) bash-4.2$ python opt/clinical_EPPs/clinical_EPPs/check_configuration.py -s aliquot_covaris_microbial.py
INFO:AUTOMATION: Searching for 'aliquot_covaris_microbial.py'.
INFO:Button: 2. Calculate Aliquot Volume
INFO:Bash string: bash -c "/home/glsai/miniconda3/envs/epp_master/bin/aliquot_covaris_microbial.py --pid {processLuid}"
INFO:Processes: ['807'] 
```

image

As far as I can tell this EPP is used in step `CG002 - Normalization of microbial samples`, which is used in workflows `CG001 Microbial WGS` and `CG002 Microbial WGS`, which are both archived.

**Comment by barrystokman** [comment]
`CG002 - Normalization of microbial samples for sequencing` uses `aliquot_sequencing_microbial.py`, not `aliquot_covaris_microbial.py`...

image

**Comment by mayabrandi** [comment]
Whats the background of this pr @barrystokman? Is it in relation to some new epp you created in cg_lims? As you mention above, the script you want to archive is still in use. Either we close this pr or we replace the script by some existing (or create a new) EPP in cg_lims.

**Comment by barrystokman** [comment]
@mayabrandi this is a draft PR, I will mark it ready when the script is implemented in the cg_lims repo :)

**Comment by seallard** [comment]
Closing this PR since any new development is done in `cg_lims` and this PR is outdated.

**Pull request closed without merging**
