### PR TITLE
script to check configurations

### PR DESCRIPTION
**Pull request by mayabrandi**
This script would cover all the situations we talked about @ingkebil . Namely answer the questions:

Search all active workflow, protol, step names in all automations and step udfs.
Where is this script used?
In what automations is this value given as argument? (Could be a process name, udf name, workflow name or whatever)
In what steps do we have this value given as process udf optional preset? (Could be a process name, udf name, workflow name or whatever)
Maybe we could have a chat about it later this week? @ingkebil

### CODE REVIEW

**Comment by ingkebil** [comment]
Yes, let's sit together on Friday for this!

**Comment by ingkebil** [comment]
Yes, Friday should work

**Comment by mayabrandi** [comment]
Sweet

**Comment by mayabrandi** [comment]
I am atm working on this script to generate output in csv for readability. So no need to review tis right now. @ingkebil

**Comment by mayabrandi** [comment]
Done. Please have a look @ingkebil

**Pull request merged**
